### ISSUE TITLE
Can you explain what houston_gt_tr and houston_gt_te keys in houston_gt.mat mean?

### ISSUE THREAD

**Issue by ucalyptus2** [mhaut/HSI-datasets#1]

**Comment by ucalyptus2** [comment]
cc: @mhaut

**Comment by mhaut** [comment]
Dear @forkbabu, thanks for your question.

"houston_gt_tr" corresponds to training labels and "houston_gt_te" corresponds to test labels. In Houston dataset, the training/test labels are disjoint. I recommend this article, in which a deeper explanation about Houston dataset is provided: https://www.sciencedirect.com/science/article/pii/S0924271619302187

Best regards.
